name: Run Bot

on:
  schedule:
    - cron: 0 16 * * * # at 16PM-UTC, 1AM-JST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      SEGA_ID: ${{ secrets.SEGA_ID }}
      SEGA_PASSWORD: ${{ secrets.SEGA_PASSWORD }}
      TZ: "Asia/Tokyo"

    steps:
      - uses: actions/checkout@v3
        with:
          ref: mucho
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install --no-dev

      - name: Run Bot
        run: |
          poetry run playcount $SEGA_ID $SEGA_PASSWORD

      - name: Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add ./playcount.csv
          git commit -m "update: $(date +%y%m%d)"
          git push origin mucho
